spring.application.name=springbootapplication
spring.h2.console.enabled=true
spring.h2.console.trace=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.schema=schema.sql
spring.datasource.data=data.sql
spring.jpa.hibernate.ddl-auto=none
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.generate_statistics=true