INSERT INTO post (title, content, created) VALUES ('Post 1', 'This is the content of the first post.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 2', 'A fascinating article that explores various topics.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 3', 'An interesting post that gives valuable insights.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 4', 'This post offers a deep dive into a specific subject.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 5', 'A short read that covers key points on the topic.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 6', 'Exploring new perspectives in this post.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 7', 'A great introduction to an often-overlooked topic.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 8', 'This post discusses real-world applications of the subject matter.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 9', 'The post is full of interesting facts and research findings.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 10', 'A must-read for anyone interested in this field of study.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 11', 'This is the content of the first post.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 12', 'A fascinating article that explores various topics.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 13', 'An interesting post that gives valuable insights.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 14', 'This post offers a deep dive into a specific subject.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 15', 'A short read that covers key points on the topic.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 16', 'Exploring new perspectives in this post.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 17', 'A great introduction to an often-overlooked topic.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 18', 'This post discusses real-world applications of the subject matter.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 19', 'The post is full of interesting facts and research findings.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 20', 'A must-read for anyone interested in this field of study.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 21', 'This is the content of the first post.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 22', 'A fascinating article that explores various topics.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 23', 'An interesting post that gives valuable insights.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 24', 'This post offers a deep dive into a specific subject.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 25', 'A short read that covers key points on the topic.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 26', 'Exploring new perspectives in this post.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 27', 'A great introduction to an often-overlooked topic.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 28', 'This post discusses real-world applications of the subject matter.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 29', 'The post is full of interesting facts and research findings.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 30', 'A must-read for anyone interested in this field of study.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 31', 'This is the content of the first post.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 32', 'A fascinating article that explores various topics.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 33', 'An interesting post that gives valuable insights.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 34', 'This post offers a deep dive into a specific subject.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 35', 'A short read that covers key points on the topic.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 36', 'Exploring new perspectives in this post.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 37', 'A great introduction to an often-overlooked topic.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 38', 'This post discusses real-world applications of the subject matter.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 39', 'The post is full of interesting facts and research findings.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 40', 'A must-read for anyone interested in this field of study.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 41', 'This is the content of the first post.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 42', 'A fascinating article that explores various topics.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 43', 'An interesting post that gives valuable insights.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 44', 'This post offers a deep dive into a specific subject.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 45', 'A short read that covers key points on the topic.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 46', 'Exploring new perspectives in this post.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 47', 'A great introduction to an often-overlooked topic.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 48', 'This post discusses real-world applications of the subject matter.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 49', 'The post is full of interesting facts and research findings.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 50', 'A must-read for anyone interested in this field of study.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 51', 'This is the content of the first post.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 52', 'A fascinating article that explores various topics.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 53', 'An interesting post that gives valuable insights.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 54', 'This post offers a deep dive into a specific subject.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 55', 'A short read that covers key points on the topic.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 56', 'Exploring new perspectives in this post.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 57', 'A great introduction to an often-overlooked topic.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 58', 'This post discusses real-world applications of the subject matter.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 59', 'The post is full of interesting facts and research findings.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 60', 'A must-read for anyone interested in this field of study.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 61', 'This is the content of the first post.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 62', 'A fascinating article that explores various topics.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 63', 'An interesting post that gives valuable insights.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 64', 'This post offers a deep dive into a specific subject.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 65', 'A short read that covers key points on the topic.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 66', 'Exploring new perspectives in this post.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 67', 'A great introduction to an often-overlooked topic.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 68', 'This post discusses real-world applications of the subject matter.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 69', 'The post is full of interesting facts and research findings.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 70', 'A must-read for anyone interested in this field of study.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 71', 'This is the content of the first post.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 72', 'A fascinating article that explores various topics.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 73', 'An interesting post that gives valuable insights.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 74', 'This post offers a deep dive into a specific subject.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 75', 'A short read that covers key points on the topic.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 76', 'Exploring new perspectives in this post.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 77', 'A great introduction to an often-overlooked topic.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 78', 'This post discusses real-world applications of the subject matter.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 79', 'The post is full of interesting facts and research findings.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 80', 'A must-read for anyone interested in this field of study.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 81', 'This is the content of the first post.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 82', 'A fascinating article that explores various topics.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 83', 'An interesting post that gives valuable insights.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 84', 'This post offers a deep dive into a specific subject.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 85', 'A short read that covers key points on the topic.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 86', 'Exploring new perspectives in this post.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 87', 'A great introduction to an often-overlooked topic.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 88', 'This post discusses real-world applications of the subject matter.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 89', 'The post is full of interesting facts and research findings.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 90', 'A must-read for anyone interested in this field of study.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 91', 'This is the content of the first post.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 92', 'A fascinating article that explores various topics.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 93', 'An interesting post that gives valuable insights.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 94', 'This post offers a deep dive into a specific subject.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 95', 'A short read that covers key points on the topic.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 96', 'Exploring new perspectives in this post.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 97', 'A great introduction to an often-overlooked topic.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 98', 'This post discusses real-world applications of the subject matter.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 99', 'The post is full of interesting facts and research findings.', NOW());
INSERT INTO post (title, content, created) VALUES ('Post 100', 'A must-read for anyone interested in this field of study.', NOW());

INSERT INTO comment (post_id, content, created) VALUES (1, 'Great post!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (1, 'Very informative, thanks!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (1, 'I totally agree with this!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (1, 'This is amazing!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (1, 'I have a question about this.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (1, 'This helped me a lot, thank you!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (1, 'Interesting perspective.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (1, 'Could you clarify this part?', NOW());
INSERT INTO comment (post_id, content, created) VALUES (1, 'Nice work, keep it up!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (1, 'I love this!', NOW());

INSERT INTO comment (post_id, content, created) VALUES (2, 'Great post!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (2, 'Very informative, thanks!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (2, 'I totally agree with this!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (2, 'This is amazing!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (2, 'I have a question about this.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (2, 'This helped me a lot, thank you!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (2, 'Interesting perspective.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (2, 'Could you clarify this part?', NOW());
INSERT INTO comment (post_id, content, created) VALUES (2, 'Nice work, keep it up!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (2, 'I love this!', NOW());

INSERT INTO comment (post_id, content, created) VALUES (3, 'Great post!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (3, 'Very informative, thanks!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (3, 'I totally agree with this!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (3, 'This is amazing!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (3, 'I have a question about this.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (3, 'This helped me a lot, thank you!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (3, 'Interesting perspective.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (3, 'Could you clarify this part?', NOW());
INSERT INTO comment (post_id, content, created) VALUES (3, 'Nice work, keep it up!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (3, 'I love this!', NOW());

INSERT INTO comment (post_id, content, created) VALUES (4, 'Great post!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (4, 'Very informative, thanks!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (4, 'I totally agree with this!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (4, 'This is amazing!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (4, 'I have a question about this.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (4, 'This helped me a lot, thank you!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (4, 'Interesting perspective.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (4, 'Could you clarify this part?', NOW());
INSERT INTO comment (post_id, content, created) VALUES (4, 'Nice work, keep it up!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (4, 'I love this!', NOW());

INSERT INTO comment (post_id, content, created) VALUES (5, 'Great post!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (5, 'Very informative, thanks!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (5, 'I totally agree with this!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (5, 'This is amazing!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (5, 'I have a question about this.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (5, 'This helped me a lot, thank you!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (5, 'Interesting perspective.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (5, 'Could you clarify this part?', NOW());
INSERT INTO comment (post_id, content, created) VALUES (5, 'Nice work, keep it up!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (5, 'I love this!', NOW());

INSERT INTO comment (post_id, content, created) VALUES (6, 'Great post!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (6, 'Very informative, thanks!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (6, 'I totally agree with this!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (6, 'This is amazing!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (6, 'I have a question about this.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (6, 'This helped me a lot, thank you!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (6, 'Interesting perspective.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (6, 'Could you clarify this part?', NOW());
INSERT INTO comment (post_id, content, created) VALUES (6, 'Nice work, keep it up!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (6, 'I love this!', NOW());

INSERT INTO comment (post_id, content, created) VALUES (7, 'Great post!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (7, 'Very informative, thanks!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (7, 'I totally agree with this!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (7, 'This is amazing!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (7, 'I have a question about this.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (7, 'This helped me a lot, thank you!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (7, 'Interesting perspective.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (7, 'Could you clarify this part?', NOW());
INSERT INTO comment (post_id, content, created) VALUES (7, 'Nice work, keep it up!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (7, 'I love this!', NOW());

INSERT INTO comment (post_id, content, created) VALUES (8, 'Great post!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (8, 'Very informative, thanks!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (8, 'I totally agree with this!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (8, 'This is amazing!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (8, 'I have a question about this.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (8, 'This helped me a lot, thank you!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (8, 'Interesting perspective.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (8, 'Could you clarify this part?', NOW());
INSERT INTO comment (post_id, content, created) VALUES (8, 'Nice work, keep it up!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (8, 'I love this!', NOW());

INSERT INTO comment (post_id, content, created) VALUES (9, 'Great post!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (9, 'Very informative, thanks!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (9, 'I totally agree with this!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (9, 'This is amazing!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (9, 'I have a question about this.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (9, 'This helped me a lot, thank you!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (9, 'Interesting perspective.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (9, 'Could you clarify this part?', NOW());
INSERT INTO comment (post_id, content, created) VALUES (9, 'Nice work, keep it up!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (9, 'I love this!', NOW());

INSERT INTO comment (post_id, content, created) VALUES (10, 'Great post!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (10, 'Very informative, thanks!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (10, 'I totally agree with this!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (10, 'This is amazing!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (10, 'I have a question about this.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (10, 'This helped me a lot, thank you!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (10, 'Interesting perspective.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (10, 'Could you clarify this part?', NOW());
INSERT INTO comment (post_id, content, created) VALUES (10, 'Nice work, keep it up!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (10, 'I love this!', NOW());

INSERT INTO comment (post_id, content, created) VALUES (11, 'Great post!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (12, 'Very informative, thanks!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (13, 'I totally agree with this!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (14, 'This is amazing!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (15, 'I have a question about this.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (16, 'This helped me a lot, thank you!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (17, 'Interesting perspective.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (18, 'Could you clarify this part?', NOW());
INSERT INTO comment (post_id, content, created) VALUES (19, 'Nice work, keep it up!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (20, 'I love this!', NOW());

INSERT INTO comment (post_id, content, created) VALUES (21, 'Awesome content, thanks for sharing!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (22, 'Really insightful, thank you!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (23, 'This is so true!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (24, 'Fantastic, I learned a lot!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (25, 'Well explained, I appreciate it!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (26, 'This is exactly what I was looking for!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (27, 'Love this topic, so relevant!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (28, 'I had no idea about this, thanks!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (29, 'Interesting take on this!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (30, 'Good to know, I値l keep this in mind.', NOW());

INSERT INTO comment (post_id, content, created) VALUES (31, 'Great post!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (32, 'Very informative, thanks!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (33, 'I totally agree with this!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (34, 'This is amazing!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (35, 'I have a question about this.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (36, 'This helped me a lot, thank you!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (37, 'Interesting perspective.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (38, 'Could you clarify this part?', NOW());
INSERT INTO comment (post_id, content, created) VALUES (39, 'Nice work, keep it up!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (40, 'I love this!', NOW());

INSERT INTO comment (post_id, content, created) VALUES (41, 'Awesome content, thanks for sharing!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (42, 'Really insightful, thank you!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (43, 'This is so true!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (44, 'Fantastic, I learned a lot!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (45, 'Well explained, I appreciate it!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (46, 'This is exactly what I was looking for!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (47, 'Love this topic, so relevant!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (48, 'I had no idea about this, thanks!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (49, 'Interesting take on this!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (50, 'Good to know, I値l keep this in mind.', NOW());

INSERT INTO comment (post_id, content, created) VALUES (51, 'Great post!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (52, 'Very informative, thanks!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (53, 'I totally agree with this!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (54, 'This is amazing!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (55, 'I have a question about this.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (56, 'This helped me a lot, thank you!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (57, 'Interesting perspective.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (58, 'Could you clarify this part?', NOW());
INSERT INTO comment (post_id, content, created) VALUES (59, 'Nice work, keep it up!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (60, 'I love this!', NOW());

INSERT INTO comment (post_id, content, created) VALUES (61, 'Awesome content, thanks for sharing!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (62, 'Really insightful, thank you!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (63, 'This is so true!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (64, 'Fantastic, I learned a lot!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (65, 'Well explained, I appreciate it!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (66, 'This is exactly what I was looking for!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (67, 'Love this topic, so relevant!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (68, 'I had no idea about this, thanks!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (69, 'Interesting take on this!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (70, 'Good to know, I値l keep this in mind.', NOW());

INSERT INTO comment (post_id, content, created) VALUES (71, 'Great post!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (72, 'Very informative, thanks!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (73, 'I totally agree with this!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (74, 'This is amazing!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (75, 'I have a question about this.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (76, 'This helped me a lot, thank you!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (77, 'Interesting perspective.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (78, 'Could you clarify this part?', NOW());
INSERT INTO comment (post_id, content, created) VALUES (79, 'Nice work, keep it up!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (80, 'I love this!', NOW());

INSERT INTO comment (post_id, content, created) VALUES (81, 'Awesome content, thanks for sharing!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (82, 'Really insightful, thank you!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (83, 'This is so true!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (84, 'Fantastic, I learned a lot!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (85, 'Well explained, I appreciate it!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (86, 'This is exactly what I was looking for!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (87, 'Love this topic, so relevant!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (88, 'I had no idea about this, thanks!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (89, 'Interesting take on this!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (90, 'Good to know, I値l keep this in mind.', NOW());

INSERT INTO comment (post_id, content, created) VALUES (91, 'Great post!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (92, 'Very informative, thanks!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (93, 'I totally agree with this!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (94, 'This is amazing!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (95, 'I have a question about this.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (96, 'This helped me a lot, thank you!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (97, 'Interesting perspective.', NOW());
INSERT INTO comment (post_id, content, created) VALUES (98, 'Could you clarify this part?', NOW());
INSERT INTO comment (post_id, content, created) VALUES (99, 'Nice work, keep it up!', NOW());
INSERT INTO comment (post_id, content, created) VALUES (100, 'I love this!', NOW());
